### Variables
@gateway = http://localhost:3000
@orderServiceUrl = http://localhost:3002
@userId = replace_this_with_id_from_createUser_response
@orderId = replace_this_with_id_from_placeOrder_response

##############################################
### IMPORTANT: TEST SEQUENCE
##############################################
### 1. Run: createUser
### 2. Wait 1-2 seconds for event processing
### 3. Run: getUserFromReadModel (use userId from step 1)
### 4. Run: placeOrder (use userId from step 1)
### 5. Wait 1-2 seconds for event processing
### 6. Run: getOrderFromReadModel (use orderId from step 4)

##############################################
### 1. USER SERVICE TESTS
##############################################

# @name createUser
POST {{gateway}}/users
Content-Type: application/json

{
    "name": "Arslan Architect",
    "email": "arslan@example.com"
}

###

# @name getUserFromReadModel
GET {{gateway}}/users/{{userId}}

##############################################
### 2. ORDER SERVICE TESTS
##############################################

# @name placeOrder
POST {{gateway}}/orders
Content-Type: application/json

{
    "userId": "{{userId}}",
    "item": "MacBook Pro M3",
    "price": 2500
}

###

# @name getOrderFromReadModel
GET {{orderServiceUrl}}/queries/orders/{{orderId}}


